os:
  - linux

language: c
sudo : required 
env:
  - PG=12
  - PG=11
  - PG=10
  - PG=9.6
  - PG=9.5

before_script:
  # creates a diff of all commits and exits the build if it only includes markdown files
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md$)'
      then
        echo "Only doc files were updated, not running the CI."
        exit
      fi
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq r-base-dev acl
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get remove --purge postgresql\*
  - sudo rm -rf /etc/postgresql /var/lib/postgresql
  - sudo apt-get install postgresql-$PG
  - sudo apt-get install postgresql-server-dev-$PG
  - echo 'local   all             postgres                                trust' | sudo tee /etc/postgresql/$PG/main/pg_hba.conf > /dev/null
  - setfacl -Rm u:postgres:rwx,d:u:travis:rwx $HOME
  - sudo pg_ctlcluster $PG main reload

script:
  - sudo pg_lsclusters
  - export USE_PGXS=1
  - SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
  - sudo  make install
  - /usr/lib/postgresql/$PG/bin/pg_config
  - psql --version 
  - make installcheck PGUSER=postgres || (cat regression.diffs && false)

after_success:
  - bash <(curl -s https://codecov.io/bash)
